import { GLOBAL_PRE_ROUTER_MIDDLEWARES } from './pre-router';
import { GLOBAL_POST_ROUTER_MIDDLEWARES } from './post-router';

export const GLOBAL_MIDDLEWARES = {
	PRE_ROUTER: GLOBAL_PRE_ROUTER_MIDDLEWARES,
	POST_ROUTER: GLOBAL_POST_ROUTER_MIDDLEWARES,
};
