import { SPECIFIC_PRE_ROUTER_MIDDLEWARES } from './pre-router';
import { SPECIFIC_POST_ROUTER_MIDDLEWARES } from './post-router';

export const SPECIFIC_MIDDLEWARES = {
	PRE_ROUTER: SPECIFIC_PRE_ROUTER_MIDDLEWARES,
	POST_ROUTER: SPECIFIC_POST_ROUTER_MIDDLEWARES,
};
